import 'dart:io';

class AppLocalizations {
  static String get currentLanguage {
    final locale = Platform.localeName;
    if (locale.startsWith('es')) return 'es';
    if (locale.startsWith('pt')) return 'pt';
    return 'en'; // default
  }
  
  static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'FungiNautas Calculator',
      'cvgCalculatorTitle': 'CVG Substrate Calculator',
      'cvgCalculatorDescription': 'Calculate the perfect CVG substrate mixture for your mushroom cultivation',
      'lcCalculatorTitle': 'LC Broth Calculator',
      'lcCalculatorDescription': 'Calculate liquid culture broth ingredients for mushroom cultivation',
      'calculating': 'Calculating...',
      'calculateCVG': 'Calculate CVG',
      'calculateLC': 'Calculate LC',
      'calculatedAmounts': 'Calculated Amounts',
      'scrollToSeeResults': 'Scroll down to see your results',
      'saveToHistory': 'Save to History',
      'shareRecipe': 'Share Recipe',
      'support': 'Support',
      'contactUs': 'Contact Us',
      'website': 'Website',
      'email': 'Email',
      'whatsapp': 'WhatsApp',
      'visitWebsite': 'Visit our website for more information',
      'sendEmail': 'Send us an email for support',
      'chatWhatsApp': 'Chat with us on WhatsApp',
      'precisionCultivationTools': 'Precision Cultivation Tools',
      'precisionCultivationToolsDescription': 'Choose your calculator below to get precise measurements for optimal mushroom cultivation results.',
      'selectCalculator': 'Select Calculator',
      'viewCalculationHistory': 'View Calculation History',
      'cocoCoirAmount': 'Coco Coir Amount (g)',
      'enterCocoCoirAmount': 'Enter coco coir amount',
      'pleaseEnterCocoCoirAmount': 'Please enter coco coir amount',
      "pleaseEnterValidPositiveNumber": "Please enter a valid positive number",
      "waterAmount": "Water Amount (ml)",
      "enterWaterAmount": "Enter water amount",
      "pleaseEnterValidNumber": "Please enter a valid number",
      "waterAmountGreaterThanZero": "Water amount must be greater than 0",
      "waterAmountTooLarge": "Water amount seems too large",
      "ingredientSelection": "Ingredient Selection",
      "honeyDescription": "Natural honey provides excellent nutrition for liquid cultures",
      "maltExtractDescription": "Malt extract offers consistent nutrients for mushroom cultivation",
      "maltExtract": "Malt Extract",
      "honey": "Honey",
      "calculationHistoryTitle": "Calculation History",
      "agarMediumCalculatorTitle": "Agar Medium Calculator",
      "agarMediumCalculatorDescription": "Calculate the perfect agar medium ingredients for PDA or MEA cultivation",
      "calculateAgar": "Calculate Agar",
      "mediumTypeSelection": "Medium Type Selection",
      "pdaDescription": "Potato Dextrose Agar",
      "meaDescription": "Malt Extract Agar",
      "pdaFullDescription": "PDA is ideal for general fungal cultivation and isolation",
      "meaFullDescription": "MEA provides excellent nutrition for mushroom mycelium growth",
      "volumeAmount": "Volume Amount (ml)",
      "enterVolumeAmount": "Enter volume amount",
      "pleaseEnterVolume": "Please enter volume amount",
      "volumeMustBeGreaterThanZero": "Volume must be greater than 0",
      "volumeTooLarge": "Volume seems too large",
      "mediumType": "Medium Type",
      "totalVolume": "Total Volume",
      "potatoBroth": "Potato Broth",
      "glucose": "Glucose (Dextrose)",
      "agar": "Agar-Agar",
      "water": "Water",
      "agarVariationNote": "Note: Agar amount per liter can vary from 15-20g depending on desired firmness (softer or firmer gel)",
      "preparationInstructions": "Preparation Instructions",
      "pdaPreparationInstructions": "To prepare potato broth: Boil potatoes for 30 minutes, then add glucose and agar, stirring well to mix. Sterilize for 20-30 minutes (maximum) in pressure cooker or autoclave (15 PSI / 121°C).",
      "meaPreparationInstructions": "Dissolve malt extract in water, then add agar, stirring well to mix. Sterilize for 20-30 minutes (maximum) in pressure cooker or autoclave (15 PSI / 121°C).",
    },
    'es': {
      'appTitle': 'Calculadora FungiNautas',
      'cvgCalculatorTitle': 'Calculadora de Sustrato CVG',
      'cvgCalculatorDescription': 'Calcula la mezcla perfecta de sustrato CVG para tu cultivo de hongos',
      'lcCalculatorTitle': 'Calculadora de Caldo LC',
      'lcCalculatorDescription': 'Calcula los ingredientes del caldo de cultivo líquido para el cultivo de hongos',
      'calculating': 'Calculando...',
      'calculateCVG': 'Calcular CVG',
      'calculateLC': 'Calcular LC',
      'calculatedAmounts': 'Cantidades Calculadas',
      'scrollToSeeResults': 'Desplázate hacia abajo para ver tus resultados',
      'saveToHistory': 'Guardar en Historial',
      'shareRecipe': 'Compartir Receta',
      'support': 'Soporte',
      'contactUs': 'Contáctanos',
      'website': 'Sitio Web',
      'email': 'Correo',
      'whatsapp': 'WhatsApp',
      'visitWebsite': 'Visita nuestro sitio web para más información',
      'sendEmail': 'Envíanos un correo para soporte',
      'chatWhatsApp': 'Chatea con nosotros en WhatsApp',
      'precisionCultivationTools': 'Herramientas de Cultivo de Precisión',
      'precisionCultivationToolsDescription': 'Elige tu calculadora a continuación para obtener medidas precisas para resultados óptimos en el cultivo de hongos.',
      'selectCalculator': 'Seleccionar Calculadora',
      'viewCalculationHistory': 'Ver Historial de Cálculo',
      'cocoCoirAmount': 'Cantidad de Fibra de Coco (g)',
      'enterCocoCoirAmount': 'Introduce la cantidad de fibra de coco',
      'pleaseEnterCocoCoirAmount': 'Por favor, introduce la cantidad de fibra de coco',
      'pleaseEnterValidPositiveNumber': 'Por favor, introduce un número positivo válido',
      'waterAmount': 'Cantidad de Agua (ml)',
      'enterWaterAmount': 'Introduce la cantidad de agua',
      'pleaseEnterValidNumber': 'Por favor, introduce un número válido',
      'waterAmountGreaterThanZero': 'La cantidad de agua debe ser mayor que 0',
      'waterAmountTooLarge': 'La cantidad de agua parece demasiado grande',
      'ingredientSelection': 'Selección de Ingredientes',
      'honeyDescription': 'La miel natural proporciona una excelente nutrición para los cultivos líquidos',
      'maltExtractDescription': 'El extracto de malta ofrece nutrientes consistentes para el cultivo de hongos',
      'maltExtract': 'Extracto de Malta',
      'honey': 'Miel',
      "agarMediumCalculatorTitle": "Calculadora de Medio de Agar",
      "agarMediumCalculatorDescription": "Calcula los ingredientes perfectos de medio de agar para cultivo PDA o MEA",
      "calculateAgar": "Calcular Agar",
      "mediumTypeSelection": "Selección de Tipo de Medio",
      "pdaDescription": "Agar Papa Dextrosa",
      "meaDescription": "Agar Extracto de Malta",
      "pdaFullDescription": "PDA es ideal para el cultivo general de hongos y aislamiento",
      "meaFullDescription": "MEA proporciona excelente nutrición para el crecimiento del micelio de hongos",
      "volumeAmount": "Cantidad de Volumen (ml)",
      "enterVolumeAmount": "Introduce la cantidad de volumen",
      "pleaseEnterVolume": "Por favor, introduce la cantidad de volumen",
      "volumeMustBeGreaterThanZero": "El volumen debe ser mayor que 0",
      "volumeTooLarge": "El volumen parece demasiado grande",
      "mediumType": "Tipo de Medio",
      "totalVolume": "Volumen Total",
      "potatoBroth": "Caldo de Papa",
      "glucose": "Glucosa (Dextrosa)",
      "agar": "Agar-Agar",
      "water": "Agua",
      "agarVariationNote": "Nota: La cantidad de agar por litro puede variar de 15-20g dependiendo de la firmeza deseada (gel más blando o más firme)",
      "preparationInstructions": "Instrucciones de Preparación",
      "pdaPreparationInstructions": "Para preparar el caldo de papa: Hervir las papas durante 30 minutos, luego agregar glucosa y agar, revolviendo bien para mezclar. Esterilizar durante 20-30 minutos (máximo) en olla a presión o autoclave (15 PSI / 121°C).",
      "meaPreparationInstructions": "Disolver el extracto de malta en agua, luego agregar agar, revolviendo bien para mezclar. Esterilizar durante 20-30 minutos (máximo) en olla a presión o autoclave (15 PSI / 121°C).",
    },
    'pt': {
      'appTitle': 'Calculadora FungiNautas',
      'cvgCalculatorTitle': 'Calculadora de Substrato CVG',
      'cvgCalculatorDescription': 'Calcule a mistura perfeita de substrato CVG para seu cultivo de cogumelos',
      'lcCalculatorTitle': 'Calculadora de Caldo LC',
      'lcCalculatorDescription': 'Calcule os ingredientes do caldo de cultura líquida para cultivo de cogumelos',
      'calculating': 'Calculando...',
      'calculateCVG': 'Calcular CVG',
      'calculateLC': 'Calcular LC',
      'calculatedAmounts': 'Quantidades Calculadas',
      'scrollToSeeResults': 'Role para baixo para ver seus resultados',
      'saveToHistory': 'Salvar no Histórico',
      'shareRecipe': 'Compartilhar Receita',
      'support': 'Suporte',
      'contactUs': 'Entre em Contato',
      'website': 'Site',
      'email': 'Email',
      'whatsapp': 'WhatsApp',
      'visitWebsite': 'Visite nosso site para mais informações',
      'sendEmail': 'Envie-nos um email para suporte',
      'chatWhatsApp': 'Converse conosco no WhatsApp',
      'precisionCultivationTools': 'Ferramentas de Cultivo de Precisão',
      'precisionCultivationToolsDescription': 'Escolha sua calculadora abaixo para obter medidas precisas para resultados ideais no cultivo de cogumelos.',
      'selectCalculator': 'Selecionar Calculadora',
      "viewCalculationHistory": "Ver Histórico de Cálculo",
      "cocoCoirAmount": "Quantidade de Fibra de Coco (g)",
      "enterCocoCoirAmount": "Insira a quantidade de fibra de coco",
      "pleaseEnterCocoCoirAmount": "Por favor, insira a quantidade de fibra de coco",
      "pleaseEnterValidPositiveNumber": "Por favor, insira um número positivo válido",
      "waterAmount": "Quantidade de Água (ml)",
      "enterWaterAmount": "Insira a quantidade de água",
      "pleaseEnterValidNumber": "Por favor, insira um número válido",
      "waterAmountGreaterThanZero": "A quantidade de água deve ser maior que 0",
      "waterAmountTooLarge": "A quantidade de água parece muito grande",
      "ingredientSelection": "Seleção de Ingredientes",
      "honeyDescription": "O mel natural fornece excelente nutrição para culturas líquidas",
      "maltExtract": "Extrato de Malte",
      "honey": "Mel",
      "calculationHistoryTitle": "Histórico de Cálculo",
      "agarMediumCalculatorTitle": "Calculadora de Meio de Ágar",
      "agarMediumCalculatorDescription": "Calcule os ingredientes perfeitos de meio de ágar para cultivo PDA ou MEA",
      "calculateAgar": "Calcular Ágar",
      "mediumTypeSelection": "Seleção de Tipo de Meio",
      "pdaDescription": "Ágar Batata Dextrose",
      "meaDescription": "Ágar Extrato de Malte",
      "pdaFullDescription": "PDA é ideal para cultivo geral de fungos e isolamento",
      "meaFullDescription": "MEA fornece excelente nutrição para o crescimento do micélio de cogumelos",
      "volumeAmount": "Quantidade de Volume (ml)",
      "enterVolumeAmount": "Insira a quantidade de volume",
      "pleaseEnterVolume": "Por favor, insira a quantidade de volume",
      "volumeMustBeGreaterThanZero": "O volume deve ser maior que 0",
      "volumeTooLarge": "O volume parece muito grande",
      "mediumType": "Tipo de Meio",
      "totalVolume": "Volume Total",
      "potatoBroth": "Caldo de Batata",
      "glucose": "Glicose (Dextrose)",
      "agar": "Ágar-Ágar",
      "water": "Água",
      "agarVariationNote": "Nota: A quantidade de ágar por litro pode variar de 15-20g dependendo da firmeza desejada (gel mais macio ou mais firme)",
      "preparationInstructions": "Instruções de Preparo",
      "pdaPreparationInstructions": "Para preparar o caldo de batata: Ferva as batatas por 30 minutos, depois adicione glicose e ágar, mexendo bem para misturar. Esterilize por 20-30 minutos (máximo) em panela de pressão ou autoclave (15 PSI / 121°C).",
      "meaPreparationInstructions": "Dissolva o extrato de malte na água, depois adicione ágar, mexendo bem para misturar. Esterilize por 20-30 minutos (máximo) em panela de pressão ou autoclave (15 PSI / 121°C).",
    }
  };

  static String translate(String key) {
    final lang = currentLanguage;
    return _localizedValues[lang]?[key] ?? _localizedValues["en"]?[key] ?? key;
  }
}